# -*- coding: utf-8 -*-
"""BananaPredictor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KA6viXFtHNKk8WsrTAliEk7Ur7-KaIWT
"""

from fastai.vision import *
from google.colab import drive

drive.mount('/content/gdrive')

folder = 'banana'
file = 'banana.csv'

folder = 'food'
file = 'food.csv'

path = Path('/content/gdrive/My Drive/foodIdentifier/')
dest = path/folder
dest.mkdir(parents=True, exist_ok=True)

path.ls()

classes = ['food','banana']

download_images(path/file, dest, max_pics=200)

download_images(path/file, dest, max_pics=20, max_workers=0)

for c in classes:
    print(c)
    verify_images(path/c, delete=True, max_size=500)

np.random.seed(42)
data = ImageDataBunch.from_folder(path, train=".", valid_pct=0.2,
        ds_tfms=get_transforms(), size=224, num_workers=4).normalize(imagenet_stats)

data.show_batch(rows=3, figsize=(7,8))

learn = cnn_learner(data, models.resnet34, metrics=error_rate)

learn.fit_one_cycle(4)

learn.save('stage-1')

learn.fit_one_cycle(2, max_lr=slice(3e-5,3e-4))

learn.save('stage-2')

learn.export()

defaults.device = torch.device('cpu')

img = open_image(path/'ban.jpg')

learn = load_learner(path)

pred_class,pred_idx,outputs = learn.predict(img)
pred_class